name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r BabbleApp/requirements.txt

      - name: Package Application
        run: |
          pyinstaller BabbleApp/babbleapp.py --onefile --distpath BabbleApp/dist/windows

      # 安装 Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup --yes

      # 检查并设置 Inno Setup 路径
      - name: Verify Inno Setup Path
        run: |
          $innoPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          if (Test-Path $innoPath) {
              Write-Host "Inno Setup found at $innoPath"
              $env:Path += ";C:\Program Files (x86)\Inno Setup 6"
          } else {
              throw "Inno Setup ISCC.exe not found in expected location."
          }

      # 生成安装包
      - name: Create Installer
        run: |
          ISCC.exe "installer_script.iss"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BabbleApp-Installer.exe  # 安装包文件的路径
          asset_name: BabbleApp-Installer.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
