name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Check out code
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r BabbleApp/requirements.txt  # 确保 requirements.txt 文件在指定位置

      # 打包应用程序
      - name: Package Application
        run: |
          pyinstaller BabbleApp/babbleapp.py --onefile --distpath BabbleApp/dist/windows  # 更新为 babbleapp.py

      # 上传打包生成的文件
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BabbleApp
          path: BabbleApp/dist/windows
