name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r BabbleApp/requirements.txt

      - name: Package Application
        run: |
          pyinstaller BabbleApp/babbleapp.py --onefile --distpath BabbleApp/dist/windows

      # 上传打包生成的文件作为 Release 资产
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # 指定 tag，可以根据项目版本更改
          release_name: Release v1.0.0  # Release 名称
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .exe to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BabbleApp/dist/windows/babbleapp.exe  # 生成的 .exe 文件路径
          asset_name: babbleapp.exe
          asset_content_type: application/octet-stream
