name: Package Application with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 更新为 v4

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新为 v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: BabbleApp
        args: --onefile BabbleApp/babbleapp.py

    - name: List output directory
      run: ls -R BabbleApp/dist

    - uses: actions/upload-artifact@v4
      with:
        name: BabbleApp
        path: BabbleApp/dist
